version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  easyocr-lexa:
    lang: python3-http-debian
    handler: ./easyocr-lexa
    image: vitezalexandra/easyocr-lexa:latest