apiVersion: apps/v1
kind: Deployment
metadata:
  name: callback-node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callback-node-server
  template:
    metadata:
      labels:
        app: callback-node-server
    spec:
      containers:
      - name: simple-node-container
        image: vitezalexandra/callback-server:latest
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: callback-node-server
spec:
  selector:
    app: callback-node-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin