apiVersion: v1
kind: Namespace
metadata:
  name: callback-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callback-node-server
  namespace: callback-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callback-node-server
  template:
    metadata:
      labels:
        app: callback-node-server
    spec:
      containers:
      - name: simple-node-container
        image: vitezalexandra/callback-server:latest
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: objectStorageEndPoint
        - name: OPENFAAS_GATEWAY
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: openfaasGateway
        - name: OCR_FUNCTION_NAME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: openfaasFunctionName
        - name: STORAGE_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: objectStorageBucket
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: callback-node-server
  namespace: callback-server
spec:
  selector:
    app: callback-node-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: callback-server
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: callback-server
data:
  objectStorageEndPoint: "minio.minio.svc.cluster.local"
  openfaasGateway: "http://gateway.openfaas.svc.cluster.local:8080"
  openfaasFunctionName: "easyocr-lexa"
  objectStorageBucket: "ocr-bucket"